import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg(process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter });

// ─── STEP 1: Fix status of previously added 18 properties to under_construction ───
const previousSlugs = [
  "rishabh-raj-arham-goregaon-west",
  "ariha-skyes-goregaon-west",
  "oberoi-elysian-goregaon-east",
  "ajmera-arham-malad-west",
  "vrindavan-malad-west",
  "aviara-malad-west",
  "sunbeam-heights-andheri-west",
  "spenta-anthea-versova-andheri-west",
  "ruparel-zinnia-borivali-west",
  "gold-leaf-borivali-west",
  "oberoi-sky-city-borivali-east",
  "lodha-altus-borivali-west",
  "mahindra-vista-kandivali-east",
  "la-mer-residences-mumbai-central",
  "aakasa-shivaji-park-dadar",
  "25-downtown-mahalaxmi",
  "siddhi-darshan-prabhadevi",
  "platinum-stellar-santacruz-west",
];

// ─── STEP 2: New properties for remaining locations ───
const newProperties = [

  // ── VILE PARLE ──
  {
    title: "Avant Park West",
    slug: "avant-park-west-vile-parle",
    location: "Irla, Vile Parle West, Mumbai",
    developerName: "Avant Group",
    config: "2 BHK, 3 BHK, 4 BHK",
    price: 6.46,
    priceLabel: "Starting ₹6.46 Cr onwards",
    carpetArea: 1113,
    area: "1,113 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security",
    description: "Avant Park West brings a new standard of premium living to Irla, Vile Parle West — one of Mumbai's most sought-after western suburb addresses. Offering spacious 2, 3 and 4 BHK residences with refined finishes, the project benefits from Vile Parle's rare combination of educational excellence, airport proximity and seamless western railway connectivity. An ideal address for established families and discerning professionals.",
  },
  {
    title: "Romell Espalier",
    slug: "romell-espalier-vile-parle-east",
    location: "Navpada, Vile Parle East, Mumbai",
    developerName: "Romell Group",
    config: "2 BHK, 3 BHK",
    price: 4.30,
    priceLabel: "Starting ₹4.30 Cr onwards",
    carpetArea: 900,
    area: "900 sq.ft. (2 BHK)",
    bedrooms: 2,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 24x7 Security, Covered Parking",
    description: "Romell Espalier in Navpada, Vile Parle East, offers premium 2 and 3 BHK residences in one of Mumbai's most established transit-oriented neighbourhoods. The development combines Romell Group's quality construction legacy with a location that delivers unmatched rail and road connectivity. An astute investment for buyers seeking a well-positioned asset in the heart of the western corridor.",
  },
  {
    title: "Chandak Vansham",
    slug: "chandak-vansham-vile-parle-west",
    location: "Vile Parle West, Mumbai",
    developerName: "Chandak Group",
    config: "3 BHK, 4 BHK",
    price: 5.31,
    priceLabel: "Starting ₹5.31 Cr onwards",
    carpetArea: 1085,
    area: "1,085 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security",
    description: "Chandak Vansham is a landmark luxury development in Vile Parle West, offering spacious 3 and 4 BHK residences designed for the refined Mumbai family. Backed by Chandak Group's consistent delivery record, this project combines premium architecture, thoughtful planning and an enviable address in one of Mumbai's most desirable western suburb micro-markets — steps from NMIMS and the international airport.",
  },
  {
    title: "Jade Park",
    slug: "jade-park-vile-parle-west",
    location: "Vile Parle West, Mumbai",
    developerName: "Jade Developers",
    config: "3 BHK, 4 BHK, 5 BHK",
    price: 5.5,
    priceLabel: "Starting ₹5.50 Cr onwards",
    carpetArea: 1300,
    area: "1,300 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Rooftop Amenities, 24x7 Security",
    description: "Jade Park in Vile Parle West presents a curated selection of 3, 4 and 5 BHK residences in a location that consistently outperforms for long-term appreciation. Generous floor plates, premium specifications and a well-designed amenity podium make this one of Vile Parle West's more distinguished current offerings — an address with both lifestyle and investment appeal.",
  },

  // ── KHAR ──
  {
    title: "Luminaara",
    slug: "luminaara-khar-west",
    location: "10th Road, Khar West, Mumbai",
    developerName: "Luminaara Developers",
    config: "2 BHK, 2.5 BHK, 3 BHK",
    price: 5.5,
    priceLabel: "Starting ₹5.50 Cr onwards",
    carpetArea: 981,
    area: "981 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Rooftop Lounge, Landscaped Gardens, 24x7 Security",
    description: "Luminaara on 10th Road, Khar West, occupies one of Mumbai's most coveted residential addresses — in the heart of a neighbourhood renowned for its boutique lifestyle, leafy streetscapes and easy access to Bandra. Offering 2, 2.5 and 3 BHK residences with premium finishes, this development is designed for buyers who value address, quality and the Khar West way of life.",
  },
  {
    title: "Yogi Sea",
    slug: "yogi-sea-khar-west",
    location: "Union Park, Pali Hill, Khar West, Mumbai",
    developerName: "Yogi Developers",
    config: "3 BHK, 4 BHK",
    price: 11.09,
    priceLabel: "Starting ₹11.09 Cr onwards",
    carpetArea: 1305,
    area: "1,305 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Sea Views, Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Concierge Services, 24x7 Security",
    description: "Yogi Sea at Union Park, Pali Hill, Khar West, is one of Mumbai's most exclusive residential addresses — where the premium of Khar meets the prestige of Pali Hill. Offering 3 and 4 BHK residences with generous proportions, this ultra-luxury development captures the rare intersection of sea views, neighbourhood prestige and lifestyle convenience that HNI buyers in this market actively seek.",
  },
  {
    title: "Pushp Vatika",
    slug: "pushp-vatika-khar-west",
    location: "12th Road, Khar West, Mumbai",
    developerName: "Pushp Developers",
    config: "4 BHK, 5 BHK",
    price: 7.60,
    priceLabel: "Starting ₹7.60 Cr onwards",
    carpetArea: 1434,
    area: "1,434 sq.ft. (4 BHK)",
    bedrooms: 4,
    bathrooms: 4,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security",
    description: "Pushp Vatika on 12th Road, Khar West, offers spacious 4 and 5 BHK residences on one of the suburb's most prestigious streets. Designed for the large urban family that refuses to compromise on space or address, this project delivers premium construction in a location that commands consistent appreciation and attracts discerning buyers from across Mumbai.",
  },
  {
    title: "Atlantis Khar West",
    slug: "atlantis-khar-west",
    location: "Khar West, Mumbai",
    developerName: "Atlantis Developers",
    config: "3 BHK, 4 BHK",
    price: 12.32,
    priceLabel: "Starting ₹12.32 Cr onwards",
    carpetArea: 1500,
    area: "1,500 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Concierge Services, Private Lift Lobbies, 24x7 Security",
    description: "Atlantis in Khar West represents the upper end of the suburb's new luxury residential supply — generous 3 and 4 BHK homes with high-end specifications in one of Mumbai's most coveted addresses. For buyers who demand the best of Khar West's lifestyle, connectivity and prestige without the constraints of smaller floor plates, Atlantis offers a rare combination.",
  },
  {
    title: "Evershine Bliss",
    slug: "evershine-bliss-khar-west",
    location: "Khar West, Mumbai",
    developerName: "Evershine Group",
    config: "2 BHK, 3 BHK, 4 BHK, Duplex",
    price: 7.95,
    priceLabel: "Starting ₹7.95 Cr onwards",
    carpetArea: 1206,
    area: "1,206 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Duplex Options, 24x7 Security",
    description: "Evershine Bliss in Khar West offers a versatile range of 2, 3 and 4 BHK residences alongside premium duplex options — catering to the full spectrum of the Khar West buyer. Backed by Evershine Group's development credentials, this project delivers quality construction, thoughtful layouts and the irreplaceable advantage of a Khar West address.",
  },
  {
    title: "AOS Genesis",
    slug: "aos-genesis-khar-west",
    location: "7th Road, Khar West, Mumbai",
    developerName: "AOS Developers",
    config: "2 BHK, 3 BHK",
    price: 4.27,
    priceLabel: "Starting ₹4.27 Cr onwards",
    carpetArea: 777,
    area: "777 sq.ft. (2 BHK)",
    bedrooms: 2,
    bathrooms: 2,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 24x7 Security, Covered Parking",
    description: "AOS Genesis on 7th Road, Khar West, offers a compelling entry point into one of Mumbai's most premium residential suburbs. With well-designed 2 and 3 BHK homes, quality finishes and the Khar West address at a relatively accessible price point, this project is well-suited for end-users and investors seeking long-term capital appreciation in a proven micro-market.",
  },

  // ── MATUNGA ──
  {
    title: "Parkway Matunga",
    slug: "parkway-matunga-east",
    location: "Matunga East, Mumbai",
    developerName: "Parkway Developers",
    config: "2 BHK",
    price: 4.80,
    priceLabel: "Starting ₹4.80 Cr onwards",
    carpetArea: 815,
    area: "815 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Landscaped Gardens, Children's Play Area, Covered Parking, 24x7 Security",
    description: "Parkway in Matunga East offers premium 2 BHK residences in one of South Mumbai's most enduring residential neighbourhoods. Known for its heritage character, top educational institutions and exceptional transit access via both Central and Western Railway lines, Matunga remains one of Mumbai's most reliably appreciating residential markets. An ideal choice for buyers seeking a quality South Mumbai address at a considered price.",
  },
  {
    title: "Paramount by Gala",
    slug: "paramount-gala-matunga-east",
    location: "Matunga East, Mumbai",
    developerName: "Gala Developers",
    config: "3 BHK",
    price: 6.25,
    priceLabel: "Starting ₹6.25 Cr onwards",
    carpetArea: 1245,
    area: "1,245 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 24x7 Security, Covered Parking",
    description: "Paramount by Gala in Matunga East presents carefully designed 3 BHK residences in the heart of central Mumbai. The development brings Gala's quality standards to a neighbourhood deeply valued by established South Mumbai families. With generous carpet areas, premium finishes and the rare availability of new supply in this location, Paramount represents a sound long-term acquisition.",
  },
  {
    title: "Rustomjee 180 Bayview",
    slug: "rustomjee-180-bayview-matunga",
    location: "Matunga West, Mumbai",
    developerName: "Rustomjee Group",
    config: "3 BHK, 4 BHK",
    price: 6.0,
    priceLabel: "Starting ₹6 Cr onwards",
    carpetArea: 1407,
    area: "1,407 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "available",
    typology: "ready_to_move",
    possession: "Ready to Move",
    featured: true,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 180-Degree Bay Views, 24x7 Security",
    description: "Rustomjee 180 Bayview in Matunga West is a completed luxury development offering signature 180-degree bay views from generous 3 and 4 BHK residences. Backed by Rustomjee Group's impeccable delivery record, this ready-to-move development offers immediate possession with premium specifications — including sweeping views of the Mahim Bay that are rarely available in this price bracket.",
  },
  {
    title: "Kalpataru Matru Ashish",
    slug: "kalpataru-matru-ashish-matunga",
    location: "Matunga, Mumbai",
    developerName: "Kalpataru Group",
    config: "3 BHK, 4 BHK",
    price: 9.0,
    priceLabel: "Starting ₹9 Cr onwards",
    carpetArea: 1130,
    area: "1,130 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "available",
    typology: "ready_to_move",
    possession: "Ready to Move",
    featured: true,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Concierge Services, 24x7 Security",
    description: "Kalpataru Matru Ashish is an iconic completed development in Matunga by one of India's most respected real estate groups. Offering ready-to-move 3 and 4 BHK residences with Kalpataru's signature quality standards, this project is positioned at the premium end of the Matunga market — ideal for established families and discerning investors seeking an iconic South Mumbai address with immediate occupancy.",
  },

  // ── SEWRI ──
  {
    title: "Lodha Aureus",
    slug: "lodha-aureus-sewri",
    location: "Sewri, Mumbai",
    developerName: "Lodha Group",
    config: "3 BHK, 4 BHK",
    price: 6.30,
    priceLabel: "Starting ₹6.30 Cr onwards",
    carpetArea: 1130,
    area: "1,130 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Sea-Facing Residences, Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Concierge Services, 24x7 Security",
    description: "Lodha Aureus in Sewri delivers the full Lodha experience — meticulous build quality, resort-calibre amenities and sea-facing residences — to one of Mumbai's most strategically positioned eastern corridors. Offering 3 and 4 BHK homes with direct views of the harbour, and benefiting from the Trans Harbour Link's transformative connectivity, this is one of the most forward-looking luxury acquisitions currently available in central Mumbai.",
  },
  {
    title: "Rustomjee Vista Bay",
    slug: "rustomjee-vista-bay-sewri",
    location: "Sewri West, Mumbai",
    developerName: "Rustomjee Group",
    config: "2 BHK, 3 BHK",
    price: 4.93,
    priceLabel: "Starting ₹4.93 Cr onwards",
    carpetArea: 1050,
    area: "1,050 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Infinity Pool, Gymnasium, Clubhouse, Landscaped Gardens, Waterfront Views, 24x7 Security",
    description: "Rustomjee Vista Bay in Sewri West brings Rustomjee's signature luxury to the Parel extension — an area benefiting enormously from Mumbai's eastern infrastructure renaissance. Offering premium 2 and 3 BHK residences with waterfront views and an infinity pool, this project is designed for buyers who recognise Sewri's transformation from overlooked to sought-after. An intelligent early acquisition in a corridor that is repricing upward.",
  },
  {
    title: "The Gateway by L&T",
    slug: "the-gateway-lt-sewri",
    location: "Sewri, Mumbai",
    developerName: "L&T Realty",
    config: "3 BHK, 4 BHK, 4.5 BHK",
    price: 11.5,
    priceLabel: "Starting ₹11.50 Cr onwards",
    carpetArea: 1258,
    area: "1,258 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "available",
    typology: "ready_to_move",
    possession: "Ready to Move",
    featured: true,
    published: true,
    amenities: "Harbour Views, Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Gardens, Concierge Services, 24x7 Security",
    description: "The Gateway by L&T Realty in Sewri is a completed landmark development offering extraordinary harbour views from premium 3, 4 and 4.5 BHK residences. Built to L&T's exacting engineering standards, this ready-to-move project delivers immediate possession with some of the most dramatic waterfront vistas available in central Mumbai — a rare combination of institutional build quality and irreplaceable views.",
  },
  {
    title: "Celestia Spaces",
    slug: "celestia-spaces-sewri",
    location: "Sewri, South Mumbai",
    developerName: "Celestia Developers",
    config: "2 BHK, 3 BHK",
    price: 4.01,
    priceLabel: "Starting ₹4.01 Cr onwards",
    carpetArea: 1207,
    area: "1,207 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "available",
    typology: "ready_to_move",
    possession: "Ready to Move",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, City Skyline Views, 24x7 Security",
    description: "Celestia Spaces in Sewri offers generously proportioned ready-to-move 2 and 3 BHK residences at one of the most compelling price points available for South Mumbai. With large carpet areas, quality finishes and immediate possession, this project suits buyers seeking a South Mumbai foothold with practical living standards — without the waiting period of an under-construction acquisition.",
  },

  // ── WORLI ──
  {
    title: "The Rivière",
    slug: "the-riviere-worli",
    location: "Worli Skyline, Worli, Mumbai",
    developerName: "The Rivière Developers",
    config: "3 BHK, 4 BHK, 5 BHK, 6 BHK, Skyplex",
    price: 11.49,
    priceLabel: "Starting ₹11.49 Cr onwards",
    carpetArea: 1752,
    area: "1,752 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Sea-Facing Residences, Infinity Pool, Spa & Wellness, Grand Clubhouse, Concierge Services, Private Lift Lobbies, 24x7 Security",
    description: "The Rivière at Worli Skyline is one of South Mumbai's most anticipated ultra-luxury addresses — offering 3, 4, 5 and 6 BHK residences alongside rare Skyplex configurations with panoramic sea views. Positioned in the heart of Worli's premium residential corridor, this development is designed for buyers who demand the absolute best of Mumbai's luxury market. Every residence at The Rivière is a statement.",
  },
  {
    title: "Embassy Citadel",
    slug: "embassy-citadel-worli",
    location: "Worli, Mumbai",
    developerName: "Embassy Group",
    config: "3 BHK, 4 BHK",
    price: 12.76,
    priceLabel: "Starting ₹12.76 Cr onwards",
    carpetArea: 1778,
    area: "1,778 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Infinity Pool, Gymnasium, Grand Clubhouse, Spa, Landscaped Gardens, Concierge Services, Private Lift Lobbies, 24x7 Security",
    description: "Embassy Citadel rises as a new luxury icon on Worli's skyline — backed by Embassy Group's institutional credibility and designed for HNI buyers who expect nothing less than the finest. Offering spacious 3 and 4 BHK residences with premium specifications, this development captures everything that makes Worli Mumbai's most desirable residential address: the sea, the connectivity, and the prestige.",
  },
  {
    title: "Godrej Trilogy",
    slug: "godrej-trilogy-worli",
    location: "Worli Seaface, Mumbai",
    developerName: "Godrej Properties",
    config: "3 BHK, 4 BHK",
    price: 20.40,
    priceLabel: "Starting ₹20.40 Cr onwards",
    carpetArea: 1700,
    area: "1,700 sq.ft. (3 BHK)",
    bedrooms: 3,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: true,
    published: true,
    amenities: "Seaface Views, Infinity Pool, Spa & Wellness, Grand Clubhouse, Concierge Services, Private Lift Lobbies, 24x7 Security",
    description: "Godrej Trilogy on Worli Seaface is one of the most prestigious residential launches in recent Mumbai history — a Godrej Properties development on one of South Mumbai's most coveted stretches of coastline. Ultra-luxury 3 and 4 BHK sea-facing residences with the brand assurance of Godrej, the address prestige of Worli Seaface, and the lifestyle standard that defines Mumbai's top 1% of real estate.",
  },
  {
    title: "Hubtown Celeste",
    slug: "hubtown-celeste-worli",
    location: "Worli, Mumbai",
    developerName: "Hubtown",
    config: "2 BHK, 3 BHK",
    price: 4.5,
    priceLabel: "Starting ₹4.50 Cr onwards",
    carpetArea: 660,
    area: "660 sq.ft. (2 BHK)",
    bedrooms: 2,
    bathrooms: 3,
    type: "apartment",
    status: "under_construction",
    typology: "new_construction",
    possession: "On Request",
    featured: false,
    published: true,
    amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 24x7 Security, Covered Parking",
    description: "Hubtown Celeste offers a compelling entry point into the Worli luxury market — premium 2 and 3 BHK residences in South Mumbai's most prestigious residential corridor at a price point that opens the address to a wider range of discerning buyers. For those seeking a Worli foothold with quality construction and a credible developer, Hubtown Celeste presents an intelligent acquisition.",
  },
];

async function main() {
  console.log("🔄 Step 1: Updating previous 18 properties to under_construction...\n");

  let updated = 0;
  for (const slug of previousSlugs) {
    await prisma.property.updateMany({
      where: { slug },
      data: { status: "under_construction" },
    });
    console.log(`✅ Updated status: ${slug}`);
    updated++;
  }
  console.log(`\n✅ ${updated} previous properties updated to under_construction.\n`);

  console.log("🏠 Step 2: Adding new properties for remaining locations...\n");

  let added = 0;
  let skipped = 0;

  for (const property of newProperties) {
    const existing = await prisma.property.findUnique({ where: { slug: property.slug } });
    if (existing) {
      console.log(`⏭️  Skipped (already exists): ${property.title}`);
      skipped++;
      continue;
    }
    await prisma.property.create({ data: property });
    console.log(`✅ Added: ${property.title} — ${property.location} [${property.status}]`);
    added++;
  }

  console.log(`\n🎉 Done! ${added} new properties added, ${skipped} skipped.`);
  console.log(`📋 Summary: 18 previous updated + ${added} new properties added.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
