import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg(process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter });

const properties = [
  { title: "Rishabh Raj Arham", slug: "rishabh-raj-arham-goregaon-west", location: "S.V. Road, Goregaon West, Mumbai", developerName: "Rishabh Raj Developers", config: "2 BHK, 3 BHK, 4 BHK", price: 4.5, priceLabel: "Starting ₹4.50 Cr onwards", carpetArea: 1404, area: "1,404 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security", description: "Positioned on the prestigious S.V. Road corridor of Goregaon West, Rishabh Raj Arham presents a curated collection of 2, 3 and 4 BHK residences across a landmark 35-storey tower. Designed for the discerning urban family, each home is crafted with generous proportions, premium finishes, and 25+ world-class amenities. Excellent metro and highway connectivity makes this an address that combines aspirational living with practical convenience." },
  { title: "Ariha Skyes", slug: "ariha-skyes-goregaon-west", location: "Goregaon West, Mumbai", developerName: "Ariha Group", config: "2 BHK, 3 BHK", price: 4.92, priceLabel: "Starting ₹4.92 Cr onwards", carpetArea: 1350, area: "1,350 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security", description: "Ariha Skyes redefines the premium residential standard in Goregaon West with thoughtfully designed 2 and 3 BHK homes in one of Mumbai's most connected western corridors. The development blends refined architecture with curated lifestyle amenities, offering residents a rare combination of urban accessibility and elevated everyday living." },
  { title: "Oberoi Elysian", slug: "oberoi-elysian-goregaon-east", location: "Yashodham, Goregaon East, Mumbai", developerName: "Oberoi Realty", config: "3 BHK, 4 BHK", price: 8.7, priceLabel: "Starting ₹8.70 Cr onwards", carpetArea: 1800, area: "1,800 sq.ft.", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Infinity Pool, Gymnasium, Grand Clubhouse, Spa & Wellness, Landscaped Gardens, Concierge Services, 24x7 Security", description: "Oberoi Elysian at Yashodham, Goregaon East, carries the full weight of the Oberoi Realty legacy — precision-engineered architecture, resort-calibre amenities, and residences that set an uncompromising standard in Mumbai's premium market. Spacious 3 and 4 BHK homes designed for families who expect more than just an address." },
  { title: "Ajmera Arham", slug: "ajmera-arham-malad-west", location: "Malad West, Mumbai", developerName: "Ajmera Realty & Infra", config: "2 BHK, 3 BHK, 4 BHK", price: 3.8, priceLabel: "Starting ₹3.80 Cr onwards", carpetArea: 1055, area: "1,055 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Rooftop Pool, Vertical Garden, Gymnasium, Clubhouse, Children's Play Area, 24x7 Security", description: "Ajmera Arham brings the credibility of one of Mumbai's most respected developers to Malad West — a location undergoing rapid premiumisation. Offering 2, 3 and 4 BHK residences with a vertical garden-clad podium, rooftop pool, and sweeping city views, this development represents exceptional value per square foot in the western suburbs." },
  { title: "Vrindavan by DB Infra", slug: "vrindavan-malad-west", location: "Malad West, Mumbai", developerName: "DB Infrastructure", config: "2 BHK, 3 BHK", price: 2.95, priceLabel: "Starting ₹2.95 Cr onwards", carpetArea: 905, area: "905 sq.ft. (2 BHK)", bedrooms: 2, bathrooms: 2, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Landscaped Gardens, Children's Play Area, Covered Parking, 24x7 Security", description: "Vrindavan by DB Infrastructure offers well-proportioned 2 and 3 BHK residences in one of Malad West's most sought-after pockets. Designed for the aspirational Mumbai family, the project combines quality construction with competitive pricing in a location that continues to attract premium capital." },
  { title: "Aviara", slug: "aviara-malad-west", location: "Malad West, Mumbai", developerName: "Aviara Developers", config: "2 BHK, 3 BHK", price: 2.39, priceLabel: "Starting ₹2.39 Cr onwards", carpetArea: 797, area: "797 sq.ft.", bedrooms: 2, bathrooms: 2, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security", description: "Aviara presents a thoughtfully planned residential development in Malad West, offering 2 and 3 BHK homes at a compelling price point for end-users and investors alike. With smart layouts, quality finishes, and proximity to key retail and commercial hubs, Aviara is designed for those who value functional luxury in an established western suburb location." },
  { title: "Sunbeam Heights", slug: "sunbeam-heights-andheri-west", location: "Adarsh Nagar, Andheri West, Mumbai", developerName: "Sunbeam Group", config: "2 BHK, 3 BHK", price: 3.6, priceLabel: "Starting ₹3.60 Cr onwards", carpetArea: 1001, area: "1,001 sq.ft. (2 BHK)", bedrooms: 2, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Rooftop Lounge, Children's Play Area, 24x7 Security", description: "Sunbeam Heights rises in the heart of Adarsh Nagar, Andheri West — one of Mumbai's most vibrant and well-connected residential pockets. Offering premium 2 and 3 BHK homes across twin towers with a striking warm facade, the project is designed for urban professionals and established families seeking a quality lifestyle address close to the metro, international airport, and BKC corporate corridor." },
  { title: "Spenta Anthea", slug: "spenta-anthea-versova-andheri-west", location: "J.P. Road, Versova, Andheri West, Mumbai", developerName: "Spenta Corporation", config: "2 BHK, 3 BHK", price: 4.87, priceLabel: "Starting ₹4.87 Cr onwards", carpetArea: 1133, area: "1,133 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Jogging Track, 24x7 Security", description: "Spenta Anthea occupies a rare address on J.P. Road, Versova — the quieter, more intimate side of Andheri West that is increasingly favoured by Mumbai's creative and professional community. Backed by Spenta Corporation's trusted development legacy, this project offers generously sized 2 and 3 BHK residences with premium specifications and a lifestyle-focused amenity deck, steps from the coastline." },
  { title: "Ruparel Zinnia", slug: "ruparel-zinnia-borivali-west", location: "Borivali West, Mumbai", developerName: "Ruparel Realty", config: "2 BHK", price: 2.08, priceLabel: "Starting ₹2.08 Cr onwards", carpetArea: 578, area: "578 sq.ft.", bedrooms: 2, bathrooms: 2, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Landscaped Gardens, Children's Play Area, Covered Parking, 24x7 Security", description: "Ruparel Zinnia is a thoughtfully planned 2 BHK residential development in Borivali West, offering a practical entry into Mumbai's western suburbs at an accessible price point. Backed by Ruparel Realty's consistent delivery record, this project suits first-time homebuyers and investors seeking a reliable asset with solid rental demand." },
  { title: "Gold Leaf", slug: "gold-leaf-borivali-west", location: "Saibaba Nagar, Borivali West, Mumbai", developerName: "Gold Leaf Developers", config: "2 BHK, 3 BHK", price: 3.79, priceLabel: "Starting ₹3.79 Cr onwards", carpetArea: 1140, area: "1,140 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Rooftop Amenity Deck, Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, 24x7 Security", description: "Gold Leaf in Saibaba Nagar, Borivali West, presents premium 2 and 3 BHK residences with an arched architectural identity and rooftop amenity level. Positioned in one of Borivali's most established residential neighbourhoods, the project offers quality construction and strong connectivity via the Western Railway and upcoming Metro Line 7." },
  { title: "Oberoi Sky City", slug: "oberoi-sky-city-borivali-east", location: "Borivali East, Mumbai", developerName: "Oberoi Realty", config: "3 BHK", price: 5.5, priceLabel: "Starting ₹5.50 Cr onwards", carpetArea: 1034, area: "1,034 sq.ft.", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Infinity Pool, Gymnasium, Grand Clubhouse, Spa, Landscaped Gardens, Concierge Services, 24x7 Security", description: "Oberoi Sky City carries the defining hallmarks of Oberoi Realty into Borivali East — a location that has rarely seen development of this calibre. Offering well-designed 3 BHK homes at an aspirational price point for the suburb, this is one of the western line's most credible luxury launches." },
  { title: "Lodha Altus", slug: "lodha-altus-borivali-west", location: "Borivali West, Mumbai", developerName: "Lodha Group", config: "3 BHK, 4 BHK", price: 5.1, priceLabel: "Starting ₹5.10 Cr onwards", carpetArea: 1086, area: "1,086 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Swimming Pool, Gymnasium, Grand Clubhouse, Landscaped Podium, Children's Play Area, Concierge Services, 24x7 Security", description: "Lodha Altus marks the arrival of one of India's most recognised developers into the Borivali West market. Offering 3 and 4 BHK residences with the build quality and amenity standards that define the Lodha brand, this project is positioned for buyers who want institutional-grade development at western suburb pricing." },
  { title: "Mahindra Vista", slug: "mahindra-vista-kandivali-east", location: "Kandivali East, Mumbai", developerName: "Mahindra Lifespaces", config: "2 BHK, 3 BHK", price: 2.9, priceLabel: "Starting ₹2.90 Cr onwards", carpetArea: 884, area: "884 sq.ft. (2 BHK)", bedrooms: 2, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Elevated Podium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security", description: "Mahindra Vista brings the trusted engineering and delivery credentials of Mahindra Lifespaces to Kandivali East — a location known for its strong residential demand and infrastructure backbone. Offering 2 and 3 BHK homes across an elevated podium development with curated amenities." },
  { title: "La Mer Residences", slug: "la-mer-residences-mumbai-central", location: "Mumbai Central, Mumbai", developerName: "La Mer Developers", config: "2 BHK, 3 BHK", price: 4.82, priceLabel: "Starting ₹4.82 Cr onwards", carpetArea: 1206, area: "1,206 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, Concierge Services, 24x7 Security", description: "La Mer Residences occupies a refined position in Mumbai Central — one of the city's most strategically located addresses, equidistant from South Mumbai's heritage precincts and the BKC commercial corridor. Offering premium 2 and 3 BHK homes with considered design and quality finishes." },
  { title: "Aakasa Shivaji Park", slug: "aakasa-shivaji-park-dadar", location: "Dadar West, Mumbai", developerName: "Aakasa Developers", config: "3 BHK", price: 5.98, priceLabel: "Starting ₹5.98 Cr onwards", carpetArea: 1150, area: "1,150 sq.ft.", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Rooftop Terrace, 24x7 Security", description: "Aakasa Shivaji Park commands one of Mumbai's most iconic addresses — overlooking the historic Shivaji Park maidan in Dadar West. Offering exclusive 3 BHK residences, this development is rare in a location where new supply is extremely limited. The combination of a landmark address and premium construction makes this one of central Mumbai's most distinguished residential opportunities." },
  { title: "25 Downtown", slug: "25-downtown-mahalaxmi", location: "Mahalaxmi, Mumbai", developerName: "25 Downtown Developers", config: "4 BHK, 5 BHK", price: 42, priceLabel: "Starting ₹42 Cr onwards", carpetArea: 3800, area: "3,800 sq.ft.", bedrooms: 4, bathrooms: 4, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Golf Course, Infinity Pool, Spa & Wellness, Grand Clubhouse, Concierge Services, Private Lift Lobbies, 24x7 Security", description: "25 Downtown at Mahalaxmi represents the upper echelon of Mumbai's ultra-luxury residential market. Offering expansive 4 and 5 BHK residences in one of South Mumbai's most coveted addresses, this development is designed for buyers for whom space, privacy, and prestige are non-negotiable." },
  { title: "Siddhi Darshan", slug: "siddhi-darshan-prabhadevi", location: "Prabhadevi, Mumbai", developerName: "Siddhi Group", config: "2 BHK, 3 BHK", price: 6.65, priceLabel: "Starting ₹6.65 Cr onwards", carpetArea: 1281, area: "1,281 sq.ft. (3 BHK)", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: false, published: true, amenities: "Swimming Pool, Gymnasium, Clubhouse, Landscaped Gardens, Children's Play Area, 24x7 Security", description: "Siddhi Darshan occupies a privileged position in Prabhadevi — steps from the revered Siddhivinayak Temple and minutes from Lower Parel's commercial heartland. Offering premium 2 and 3 BHK residences in one of Mumbai's most spiritually and socially significant neighbourhoods." },
  { title: "Platinum Stellar", slug: "platinum-stellar-santacruz-west", location: "Main Avenue, Santacruz West, Mumbai", developerName: "Platinum Corp", config: "3 BHK, 4 BHK, 5 BHK", price: 18, priceLabel: "Starting ₹18 Cr onwards", carpetArea: 2000, area: "2,000 sq.ft.", bedrooms: 3, bathrooms: 3, type: "apartment", status: "available", typology: "new_construction", possession: "On Request", featured: true, published: true, amenities: "Infinity Pool, Gymnasium, Grand Clubhouse, Spa, Landscaped Terrace, Concierge Services, Private Lift Lobbies, 24x7 Security", description: "Platinum Stellar rises on Main Avenue, Santacruz West — an address that sits at the confluence of old Mumbai elegance and new luxury demand. Offering generously scaled 3, 4 and 5 BHK residences in a landmark high-rise, this development caters to discerning families and HNI buyers who value Santacruz West's unique positioning." },
];

async function main() {
  console.log("🏠 Seeding 18 properties...\n");
  let added = 0;
  let skipped = 0;

  for (const property of properties) {
    const existing = await prisma.property.findUnique({ where: { slug: property.slug } });
    if (existing) {
      console.log(`⏭️  Skipped (already exists): ${property.title}`);
      skipped++;
      continue;
    }
    await prisma.property.create({ data: property });
    console.log(`✅ Added: ${property.title} — ${property.location}`);
    added++;
  }

  console.log(`\n🎉 Done! ${added} added, ${skipped} skipped.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });